### ISSUE TITLE
Need a Mac

### ISSUE THREAD

**Issue by rowland17** [Kionte/SubStation-#1]
we need a mac to run our code

**Comment by Kionte** [comment]
Finished downloading on Mac you should be good now.

Sent from my iPhone

On Jun 28, 2016, at 4:41 PM, rowland17 <notifications@github.com<mailto:notifications@github.com>> wrote:


we need a mac to run our code

-

**Comment by rowland17** [comment]
do you mind if i have your password?

**Comment by Kionte** [comment]
For my Mac or xamerin?

Sent from my iPhone

On Jun 30, 2016, at 12:22 PM, rowland17 <notifications@github.com<mailto:notifications@github.com>> wrote:


do you mind if i have your password?

-

**Comment by rowland17** [comment]
mac

**Comment by rowland17** [comment]
I got the mac mini from clint and we are now connected via visual studio
